### ISSUE TITLE
Roadmap to V1

### ISSUE THREAD

**Issue by Kocal** [Kocal/Alderiate-Live#1]
- [x] Supprimer le code de l'API qui n'est plus utilisé, depuis qu'on utilise https://alderiate.com/twitch.json (#2)
- [x] Supprimer le code actuel de l'extension pour utiliser [vue-web-extension](https://github.com/Kocal/vue-web-extension) (#4)
- [x] Utiliser [standard-version](https://github.com/conventional-changelog/standard-version) (#7)
- [x] Utiliser la licence MIT (#6)
- [x] Utiliser Travis (https://github.com/Kocal/Solary/blob/master/.travis.yml) (#5)
- [x] Ré-écrire l'extension de zéro (modernisation pour l'instant, les features arriveront plus tard)  (#8)
